# Generated by Django 6.0.5 on 2026-05-21 00:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Color')),
                ('hex_code', models.CharField(default='#FFFFFF', help_text='Ejemplo: #FF0000 para rojo', max_length=7, verbose_name='Código Hexadecimal')),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colores',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código de Cupón')),
                ('discount_type', models.CharField(choices=[('percentage', 'Porcentaje (%)'), ('fixed', 'Monto Fijo')], default='percentage', max_length=20, verbose_name='Tipo de Descuento')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor de Descuento')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('valid_from', models.DateTimeField(verbose_name='Válido desde')),
                ('valid_to', models.DateTimeField(verbose_name='Válido hasta')),
            ],
            options={
                'verbose_name': 'Cupón de Descuento',
                'verbose_name_plural': 'Cupones de Descuento',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Talla/Tamaño')),
            ],
            options={
                'verbose_name': 'Talla',
                'verbose_name_plural': 'Tallas',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('address', models.CharField(max_length=250, verbose_name='Dirección de Envío')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('country', models.CharField(default='Paraguay', max_length=100, verbose_name='País')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total del Pedido')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Monto Descontado')),
                ('paid', models.BooleanField(default=False, verbose_name='¿Está pagado?')),
                ('payment_id', models.CharField(blank=True, max_length=150, null=True, verbose_name='ID de Transacción')),
                ('status', models.CharField(choices=[('pending', 'Pendiente de Pago'), ('paid', 'Pagado'), ('shipped', 'Enviado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado de la Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='store.coupon', verbose_name='Cupón aplicado')),
            ],
            options={
                'verbose_name': 'Pedido / Orden',
                'verbose_name_plural': 'Pedidos / Órdenes',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio base (Gs. o USD)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Imagen principal')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock disponible')),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Dejar en blanco si usa el precio base del producto', max_digits=12, null=True, verbose_name='Precio alternativo')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.color', verbose_name='Color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.product', verbose_name='Producto')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.size', verbose_name='Talla')),
            ],
            options={
                'verbose_name': 'Variante de Producto',
                'verbose_name_plural': 'Variantes de Productos',
                'unique_together': {('product', 'color', 'size')},
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio de compra')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order', verbose_name='Pedido')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Producto')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.productvariant', verbose_name='Variante')),
            ],
            options={
                'verbose_name': 'Ítem de Pedido',
                'verbose_name_plural': 'Ítems de Pedidos',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, verbose_name='Nombre de Usuario')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación (1-5)')),
                ('comment', models.TextField(verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Reseña / Calificación',
                'verbose_name_plural': 'Reseñas / Calificaciones',
                'ordering': ('-created_at',),
            },
        ),
    ]
